version: "3.9"

services:
  yt2radarr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yt2radarr
    restart: unless-stopped

    ports:
      - "5010:5000"
    volumes:
      - /Users/gil/Downloads/test:/Movies
      - "${HOME}/Library/Application Support/Google/Chrome/Default:/root/.config/google-chrome/Default:ro"

