name: pylint

on:
  pull_request:
    branches:
      - '**'

jobs:
  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py')
